In [19]:
#performing imports
import pandas as pd

In [20]:
df = pd.read_csv("Module 2.csv")
df

     ID           Campus                                           Comments
0    32      Bakersfield                                                NaN
1    36            Chico  25 - Parental Pressure on Major Choice: I teac...
2   128            Chico  27-sense of belonging on campus\n\nMany of my ...
3    25  Dominguez Hills  The barriers listed in the EAB document that s...
4    91  Dominguez Hills  I teach graduate students in the School and Co...
5   186  Dominguez Hills  The three barriers that I selected are 19, 50 ...
6    11         East Bay  The three barriers that have impacted students...
7    81         East Bay  I teach music at CSUEB. If I had to choose onl...
8   201         East Bay  In my previous experience as a faculty member,...
9    35           Fresno  While the assignment calls for us to pick thre...
10   15       Long Beach  67. Effect of pre-requisite course sequencing\...
11   97       Long Beach  15, 17, 19 are resonating with me. It is a com...
12   22     Monterey Bay  As a lecturer in the Master's in Social Progra...
13    6       Northridge  Wow, this is quite the list and it is hard to ...
14   94       Northridge  In my courses, students have been most impacte...
15   12       Sacramento  I've identified a few obstacles within my acad...
16   27   San Bernardino  There are a lot of barriers on here that I've ...
17  139   San Bernardino  As many have mentioned, it is difficult to onl...
18  212   San Bernardino  17) Student expectations of their ability to s...
19    7    San Francisco                                                NaN
20   95    San Francisco  97 (student debt) - The student debt has many ...

In [21]:
pd.isna(df)

       ID  Campus  Comments
0   False   False      True
1   False   False     False
2   False   False     False
3   False   False     False
4   False   False     False
5   False   False     False
6   False   False     False
7   False   False     False
8   False   False     False
9   False   False     False
10  False   False     False
11  False   False     False
12  False   False     False
13  False   False     False
14  False   False     False
15  False   False     False
16  False   False     False
17  False   False     False
18  False   False     False
19  False   False      True
20  False   False     False

In [24]:
df = df.dropna(axis=0, how='any').reset_index(drop=True)
df

     ID           Campus                                           Comments
0    36            Chico  25 - Parental Pressure on Major Choice: I teac...
1   128            Chico  27-sense of belonging on campus\n\nMany of my ...
2    25  Dominguez Hills  The barriers listed in the EAB document that s...
3    91  Dominguez Hills  I teach graduate students in the School and Co...
4   186  Dominguez Hills  The three barriers that I selected are 19, 50 ...
5    11         East Bay  The three barriers that have impacted students...
6    81         East Bay  I teach music at CSUEB. If I had to choose onl...
7   201         East Bay  In my previous experience as a faculty member,...
8    35           Fresno  While the assignment calls for us to pick thre...
9    15       Long Beach  67. Effect of pre-requisite course sequencing\...
10   97       Long Beach  15, 17, 19 are resonating with me. It is a com...
11   22     Monterey Bay  As a lecturer in the Master's in Social Progra...
12    6       Northridge  Wow, this is quite the list and it is hard to ...
13   94       Northridge  In my courses, students have been most impacte...
14   12       Sacramento  I've identified a few obstacles within my acad...
15   27   San Bernardino  There are a lot of barriers on here that I've ...
16  139   San Bernardino  As many have mentioned, it is difficult to onl...
17  212   San Bernardino  17) Student expectations of their ability to s...
18   95    San Francisco  97 (student debt) - The student debt has many ...

In [ ]:
# Step - 1 : Prelabelling the Data set, zero shot approach (Bart-Facebook-MNLI)